version: '3.8'

services:

  redis:
    image: 'redis:5.0.5'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "src.app:flask_app"
    env_file:
      - '.env'
    volumes:
      - '.:/deadlyai'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: celery worker -A wsgi_app.celery --loglevel=info --pool=solo
    env_file:
      - '.env'
    volumes:
      - '.:/deadlyai'
      
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://:devpassword@redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - 5555:5555

volumes:
  redis:
